spring:
  datasource:
    url: jdbc:sqlserver://chandanserverpatna.database.windows.net:1433;database=chandan;user=chandankumar06@chandanserverpatna;password=chandanKumar@9;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: chandankumar06
    password: chandanKumar@9
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9193


